// Regenerates src/fonts-data.ts by base64-embedding the woff2 files from the
// installed @fontsource packages. Embedding (rather than fetching at render
// time) makes every render deterministic and immune to network/fetch stalls.
//
// Usage:  node scripts/embed-fonts.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");

const FONTS = {
  ROBOTO_400: "@fontsource/roboto/files/roboto-latin-400-normal.woff2",
  ROBOTO_500: "@fontsource/roboto/files/roboto-latin-500-normal.woff2",
  ROBOTO_700: "@fontsource/roboto/files/roboto-latin-700-normal.woff2",
  ROBOTO_900: "@fontsource/roboto/files/roboto-latin-900-normal.woff2",
  MONO_400: "@fontsource/roboto-mono/files/roboto-mono-latin-400-normal.woff2",
  MONO_500: "@fontsource/roboto-mono/files/roboto-mono-latin-500-normal.woff2",
  MONO_700: "@fontsource/roboto-mono/files/roboto-mono-latin-700-normal.woff2",
};

let out =
  "// AUTO-GENERATED by scripts/embed-fonts.mjs — do not edit by hand.\n" +
  "// Base64-embedded Roboto / Roboto Mono woff2 (latin) for fetch-free, deterministic renders.\n" +
  "/* eslint-disable */\n";

for (const [name, rel] of Object.entries(FONTS)) {
  const b64 = readFileSync(resolve(root, "node_modules", rel)).toString("base64");
  out += `export const ${name} = "data:font/woff2;base64,${b64}";\n`;
}

writeFileSync(resolve(root, "src/fonts-data.ts"), out);
console.log(`Wrote src/fonts-data.ts (${out.length} bytes)`);
