export const PREMIER_LEAGUE_CLUBS = [
  "Arsenal",
  "Aston Villa",
  "Bournemouth",
  "Brentford",
  "Brighton",
  "Chelsea",
  "Crystal Palace",
  "Everton",
  "Fulham",
  "Ipswich Town",
  "Leicester City",
  "Liverpool",
  "Man City",
  "Man United",
  "Newcastle",
  "Nottingham Forest",
  "Southampton",
  "Spurs",
  "West Ham",
  "Wolves",
]

export const FIFA_CLUBS = [
  // Premier League
  "Arsenal",
  "Aston Villa",
  "Bournemouth",
  "Brentford",
  "Brighton",
  "Chelsea",
  "Crystal Palace",
  "Everton",
  "Fulham",
  "Ipswich Town",
  "Leicester City",
  "Liverpool",
  "Man City",
  "Man United",
  "Newcastle",
  "Nottingham Forest",
  "Southampton",
  "Spurs",
  "West Ham",
  "Wolves",

  // La Liga
  "Real Madrid",
  "Barcelona",
  "Atletico Madrid",
  "Athletic Bilbao",
  "Real Sociedad",
  "Villarreal",
  "Real Betis",
  "Valencia",
  "Sevilla",
  "Celta Vigo",
  "Osasuna",
  "Getafe",
  "Las Palmas",
  "Girona",
  "Mallorca",
  "Rayo Vallecano",
  "Alaves",
  "Leganes",
  "Espanyol",
  "Valladolid",

  // Serie A
  "Juventus",
  "Inter Milan",
  "AC Milan",
  "Napoli",
  "Roma",
  "Lazio",
  "Atalanta",
  "Fiorentina",
  "Bologna",
  "Torino",
  "Udinese",
  "Empoli",
  "Parma",
  "Cagliari",
  "Hellas Verona",
  "Como",
  "Lecce",
  "Genoa",
  "Monza",
  "Venezia",

  // Bundesliga
  "Bayern Munich",
  "Borussia Dortmund",
  "RB Leipzig",
  "Bayer Leverkusen",
  "Eintracht Frankfurt",
  "SC Freiburg",
  "Union Berlin",
  "VfB Stuttgart",
  "Werder Bremen",
  "Borussia Monchengladbach",
  "Mainz",
  "Augsburg",
  "Heidenheim",
  "Hoffenheim",
  "St. Pauli",
  "VfL Bochum",
  "Holstein Kiel",
  "Wolfsburg",

  // Ligue 1
  "PSG",
  "AS Monaco",
  "Marseille",
  "Lille",
  "Lyon",
  "Nice",
  "Lens",
  "Strasbourg",
  "Brest",
  "Rennes",
  "Reims",
  "Toulouse",
  "Nantes",
  "Auxerre",
  "Angers",
  "Saint-Etienne",
  "Le Havre",
  "Montpellier",

  // Eredivisie (Dutch League)
  "Ajax",
  "PSV",
  "Feyenoord",
  "AZ Alkmaar",
  "FC Twente",
  "FC Utrecht",
  "Go Ahead Eagles",
  "Heerenveen",
  "NEC Nijmegen",
  "PEC Zwolle",
  "Sparta Rotterdam",
  "Willem II",
  "Fortuna Sittard",
  "NAC Breda",
  "RKC Waalwijk",
  "Heracles",
  "FC Groningen",
  "Almere City",

  // Primeira Liga (Portuguese League)
  "Benfica",
  "Porto",
  "Sporting CP",
  "SC Braga",
  "Vitoria Guimaraes",
  "Rio Ave",
  "Moreirense",
  "Casa Pia",
  "Gil Vicente",
  "Famalicao",
  "Santa Clara",
  "Boavista",
  "Estrela",
  "Arouca",
  "Estoril",
  "AVS",
  "Nacional",
  "Farense",

  // Belgian Pro League
  "Club Brugge",
  "Anderlecht",
  "Royal Antwerp",
  "Genk",
  "Standard Liege",
  "Gent",
  "Union Saint-Gilloise",
  "Mechelen",
  "Cercle Brugge",
  "Charleroi",
  "Kortrijk",
  "Westerlo",
  "Sint-Truiden",
  "Eupen",
  "Dender",
  "Beerschot",

  // Scottish Premiership
  "Celtic",
  "Rangers",
  "Aberdeen",
  "Hearts",
  "Hibernian",
  "Dundee United",
  "St Mirren",
  "Motherwell",
  "Kilmarnock",
  "Ross County",
  "St Johnstone",
  "Dundee",

  // Turkish Super Lig
  "Galatasaray",
  "Fenerbahce",
  "Besiktas",
  "Trabzonspor",
  "Basaksehir",
  "Adana Demirspor",
  "Antalyaspor",
  "Konyaspor",
  "Sivasspor",
  "Kasimpasa",
  "Alanyaspor",
  "Rizespor",
  "Gaziantep FK",
  "Kayserispor",
  "Hatayspor",
  "Goztepe",
  "Samsunspor",
  "Bodrumspor",

  // MLS (Major League Soccer)
  "Inter Miami",
  "LA Galaxy",
  "LAFC",
  "Atlanta United",
  "Seattle Sounders",
  "Portland Timbers",
  "New York City FC",
  "New York Red Bulls",
  "Philadelphia Union",
  "Toronto FC",
  "Montreal Impact",
  "Vancouver Whitecaps",
  "Chicago Fire",
  "Columbus Crew",
  "DC United",
  "Orlando City",
  "Nashville SC",
  "Austin FC",
  "FC Cincinnati",
  "Charlotte FC",
  "Real Salt Lake",
  "Colorado Rapids",
  "Sporting Kansas City",
  "Minnesota United",
  "Houston Dynamo",
  "FC Dallas",
  "San Jose Earthquakes",
  "St. Louis City SC",

  // Brazilian Serie A
  "Flamengo",
  "Palmeiras",
  "Corinthians",
  "Sao Paulo",
  "Santos",
  "Fluminense",
  "Atletico Mineiro",
  "Cruzeiro",
  "Botafogo",
  "Vasco da Gama",
  "Internacional",
  "Gremio",
  "Athletico Paranaense",
  "Fortaleza",
  "Bahia",
  "Bragantino",
  "Juventude",
  "Criciuma",
  "Vitoria",
  "Cuiaba",
  "Atletico Goianiense",
  "Ceara",
  "Chapecoense",
  "Coritiba",
  "Sport Recife",
  "Avai",
  "Goias",
  "America Mineiro",
  "Ponte Preta",
  "Guarani",

  // Argentine Primera División
  "River Plate",
  "Boca Juniors",
  "Racing Club",
  "Independiente",
  "San Lorenzo",
  "Estudiantes",
  "Velez Sarsfield",
  "Lanus",
  "Newells Old Boys",
  "Rosario Central",
  "Talleres",
  "Godoy Cruz",
  "Gimnasia La Plata",
  "Huracan",
  "Tigre",
  "Platense",
  "Banfield",
  "Defensa y Justicia",
  "Argentinos Juniors",
  "Belgrano",
  "Instituto",
  "Deportivo Riestra",
  "Central Cordoba",
  "Independiente Rivadavia",
  "Atletico Tucuman",
  "Union",
  "Sarmiento",
  "Barracas Central",

  // Saudi Pro League
  "Al Hilal",
  "Al Nassr",
  "Al Ittihad",
  "Al Ahli",
  "Al Shabab",
  "Al Ettifaq",
  "Al Fateh",
  "Al Feiha",
  "Al Hazem",
  "Al Khaleej",
  "Al Okhdood",
  "Al Raed",
  "Al Riyadh",
  "Al Taawoun",
  "Al Tai",
  "Al Wehda",
  "Abha",
  "Damac",

  // Championship (English Second Tier)
  "Leicester City",
  "Leeds United",
  "Burnley",
  "Sheffield United",
  "Luton Town",
  "Middlesbrough",
  "West Bromwich Albion",
  "Blackburn Rovers",
  "Norwich City",
  "Coventry City",
  "Hull City",
  "Stoke City",
  "Swansea City",
  "Watford",
  "Millwall",
  "Bristol City",
  "Sheffield Wednesday",
  "Preston North End",
  "Derby County",
  "Cardiff City",
  "Queens Park Rangers",
  "Oxford United",
  "Portsmouth",
  "Plymouth Argyle",

  // Liga MX (Mexican League)
  "Club America",
  "Chivas Guadalajara",
  "Cruz Azul",
  "Pumas UNAM",
  "Tigres UANL",
  "Monterrey",
  "Santos Laguna",
  "Pachuca",
  "Leon",
  "Atlas",
  "Toluca",
  "Puebla",
  "Necaxa",
  "Queretaro",
  "FC Juarez",
  "Tijuana",
  "Mazatlan",
  "Atletico San Luis",

  // Other Notable International Clubs
  "Olympiacos",
  "Panathinaikos",
  "Red Star Belgrade",
  "Partizan Belgrade",
  "Dinamo Zagreb",
  "Hajduk Split",
  "Sparta Prague",
  "Slavia Prague",
  "Shakhtar Donetsk",
  "Dynamo Kyiv",
  "CSKA Moscow",
  "Spartak Moscow",
  "Zenit St Petersburg",
  "Lokomotiv Moscow",
  "Maccabi Tel Aviv",
  "Hapoel Beer Sheva",
  "Al Hilal",
  "Al Nassr",
  "Al Ahly",
  "Zamalek",
  "Kaizer Chiefs",
  "Orlando Pirates",
  "Mamelodi Sundowns",
].sort()

export const CONSOLE_OPTIONS = [
  { value: "PS5", label: "PlayStation 5" },
  { value: "XBOX", label: "Xbox Series X/S" },
  { value: "PC", label: "PC" },
]

export const LEAGUE_STATUS = {
  DRAFT: "DRAFT",
  ACTIVE: "ACTIVE",
  COMPLETE: "COMPLETE",
} as const

export const FIXTURE_STATUS = {
  SCHEDULED: "SCHEDULED",
  PLAYED: "PLAYED",
  CANCELLED: "CANCELLED",
} as const

export const USER_ROLES = {
  PLAYER: "PLAYER",
  ADMIN: "ADMIN",
} as const
